# REG Minimal Run — Full-Scale Regression Modeling (Minimal / Controlled)

**Two-Stage Architecture — Stage 2: Quantity Prediction**

**Strategy:** Defensible TEST decision without multi-hour model runs.

- No Ridge (OHE on full data too slow)
- No LightGBM / CatBoost
- No full Random Forest (100 trees)
- HistGradientBoosting with OrdinalEncoding as primary model
- Light RF (30 trees) only if HistGB shows clear RMSE gain over Always-1
- VAL locked — `reg_val.csv` never loaded

**Outputs → `Modellierung/REG/`**

In [1]:
# ── PHASE 1 — Setup & Data Loading ─────────────────────────────────────────
import warnings
warnings.filterwarnings("ignore")

import time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

from sklearn.metrics import (mean_squared_error, mean_absolute_error,
                              median_absolute_error, r2_score)
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import (HistGradientBoostingRegressor,
                               RandomForestRegressor)

# ── Paths ──────────────────────────────────────────────────────────────────
BASE     = Path(r"c:\Users\karim\OneDrive - FHNW\Documents\Analytics Project Code")
DATA_DIR = BASE / "Feature Engineering" / "outputs" / "orange_exports"
OUT_DIR  = BASE / "Modellierung" / "REG"
OUT_DIR.mkdir(parents=True, exist_ok=True)

TRAIN_PATH = DATA_DIR / "reg_train_full.csv"
TEST_PATH  = DATA_DIR / "reg_test.csv"
# VAL_PATH intentionally not defined — never loaded

print(f"Train : {TRAIN_PATH}")
print(f"Test  : {TEST_PATH}")
print(f"Output: {OUT_DIR}")

Train : c:\Users\karim\OneDrive - FHNW\Documents\Analytics Project Code\Feature Engineering\outputs\orange_exports\reg_train_full.csv
Test  : c:\Users\karim\OneDrive - FHNW\Documents\Analytics Project Code\Feature Engineering\outputs\orange_exports\reg_test.csv
Output: c:\Users\karim\OneDrive - FHNW\Documents\Analytics Project Code\Modellierung\REG

In [2]:
# ── PHASE 1 cont. — Load Data ───────────────────────────────────────────────
t0 = time.time()
train = pd.read_csv(TRAIN_PATH)
test  = pd.read_csv(TEST_PATH)
print(f"Loaded in {time.time()-t0:.1f}s")
print(f"\nTrain shape : {train.shape}")
print(f"Test  shape : {test.shape}")

print("\n── Train columns ──")
print(list(train.columns))
print("\n── Test columns ──")
print(list(test.columns))

print("\n── First 5 rows (train) ──")
display(train.head())

Loaded in 1.3s

Train shape : (332546, 27)
Test  shape : (82403, 27)

── Train columns ──
['day', 'day_7', 'day_14', 'day_30', 'price', 'competitorPrice', 'genericProduct', 'salesIndex', 'category_norm', 'pharmForm_norm', 'campaignIndex_norm', 'manufacturer_freq', 'group34', 'is_multipack', 'price_diff', 'price_discount', 'price_diff_bin', 'discount_bin', 'pid_total_events', 'click_time', 'basket_time', 'order_time', 'group12_order', 'group34_order', 'pid_prob', 'pid_segment', 'quantity']

── Test columns ──
['day', 'day_7', 'day_14', 'day_30', 'price', 'competitorPrice', 'genericProduct', 'salesIndex', 'category_norm', 'pharmForm_norm', 'campaignIndex_norm', 'manufacturer_freq', 'group34', 'is_multipack', 'price_diff', 'price_discount', 'price_diff_bin', 'discount_bin', 'pid_total_events', 'click_time', 'basket_time', 'order_time', 'group12_order', 'group34_order', 'pid_prob', 'pid_segment', 'quantity']

── First 5 rows (train) ──

,day,day_7,day_14,day_30,price,competitorPrice,genericProduct,salesIndex,category_norm,pharmForm_norm,...,discount_bin,pid_total_events,click_time,basket_time,order_time,group12_order,group34_order,pid_prob,pid_segment,quantity
0,33,5,5,3,7.28,8.22,0,40,NaN,TAB,...,Q16,1,0,1,0,0.185481,0.236026,0.230087,Tail,1.0
1,35,7,7,5,10.08,8.22,0,40,NaN,TAB,...,Q02,0,0,0,0,0.185481,0.236026,0.230087,Tail,1.0
2,40,5,12,10,6.42,7.88,0,40,C_2.0,GLO,...,Q17,2,1,1,0,0.185481,0.236026,0.000000,Tail,1.0
3,50,1,8,20,19.31,17.16,0,53,C_3.0,TRA,...,Q06,12,12,0,0,0.171828,0.192525,0.000000,Mid,1.0
4,34,6,6,4,10.08,8.68,0,40,C_2.0,TAB,...,Q02,0,0,0,0,0.185481,0.236026,0.230087,Mid,1.0

In [3]:
# ── PHASE 1 cont. — quantity distribution ──────────────────────────────────
TARGET = "quantity"
assert TARGET in train.columns, "quantity missing from train"
assert TARGET in test.columns,  "quantity missing from test"

y_train = train[TARGET].copy()
y_test  = test[TARGET].copy()

assert y_train.dtype in [np.int64, np.float64, int, float], "quantity not numeric"
assert (y_train >= 1).all(), "quantity < 1 found in train"
assert (y_test  >= 1).all(), "quantity < 1 found in test"

def qty_summary(s, label):
    print(f"\n── {label} quantity ──")
    print(f"  n        : {len(s):,}")
    print(f"  mean     : {s.mean():.4f}")
    print(f"  median   : {s.median():.4f}")
    print(f"  min      : {s.min()}")
    print(f"  max      : {s.max()}")
    print(f"  p95      : {s.quantile(0.95):.2f}")
    print(f"  p99      : {s.quantile(0.99):.2f}")
    print(f"  qty=1    : {(s==1).mean()*100:.1f}%  ({(s==1).sum():,})")
    print(f"  qty>1    : {(s>1).mean()*100:.1f}%  ({(s>1).sum():,})")
    print(f"  qty>=3   : {(s>=3).mean()*100:.1f}%  ({(s>=3).sum():,})")

qty_summary(y_train, "TRAIN")
qty_summary(y_test,  "TEST")

── TRAIN quantity ──
  n        : 332,546
  mean     : 1.3310
  median   : 1.0000
  min      : 1.0
  max      : 306.0
  p95      : 3.00
  p99      : 5.00
  qty=1    : 81.2%  (270,049)
  qty>1    : 18.8%  (62,497)
  qty>=3   : 5.2%  (17,377)

── TEST quantity ──
  n        : 82,403
  mean     : 1.3508
  median   : 1.0000
  min      : 1.0
  max      : 100.0
  p95      : 3.00
  p99      : 5.00
  qty=1    : 80.3%  (66,152)
  qty>1    : 19.7%  (16,251)
  qty>=3   : 5.6%  (4,612)

In [4]:
# ── PHASE 2 — Leakage Check ─────────────────────────────────────────────────
LEAKAGE_COLS = [
    "lineID", "revenue", "order", "click", "basket",
    "quantity_class", "qty_suspicious", "num_pid_order"
]

present_leak = [c for c in LEAKAGE_COLS if c in train.columns]
print(f"Leakage columns found in train : {present_leak}")

DROP_COLS = present_leak + [TARGET]

X_train = train.drop(columns=[c for c in DROP_COLS if c in train.columns])
X_test  = test.drop( columns=[c for c in DROP_COLS if c in test.columns])

# Align columns (test may have extra/missing)
shared_cols = [c for c in X_train.columns if c in X_test.columns]
X_train = X_train[shared_cols]
X_test  = X_test[shared_cols]

print(f"\nRemoved leakage columns   : {present_leak}")
print(f"Final feature count       : {len(shared_cols)}")
print(f"X_train shape             : {X_train.shape}")
print(f"X_test  shape             : {X_test.shape}")
assert list(X_train.columns) == list(X_test.columns), "Column mismatch after alignment"
print("\nColumn alignment: OK")

Leakage columns found in train : []

Removed leakage columns   : []
Final feature count       : 26
X_train shape             : (332546, 26)
X_test  shape             : (82403, 26)

Column alignment: OK

In [5]:
# ── PHASE 3 — Baselines on TEST ────────────────────────────────────────────

BASELINE_MEDIAN = float(y_train.median())
BASELINE_MEAN   = float(y_train.mean())

print(f"Train median : {BASELINE_MEDIAN}")
print(f"Train mean   : {BASELINE_MEAN:.4f}")

def mape_safe(y_true, y_pred):
    mask = y_true != 0
    return np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) if mask.any() else np.nan

def compute_metrics(y_true, y_pred, label=""):
    y_true = np.array(y_true, dtype=float)
    y_pred = np.array(y_pred, dtype=float)
    mse  = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae  = mean_absolute_error(y_true, y_pred)
    mdae = median_absolute_error(y_true, y_pred)
    mape = mape_safe(y_true, y_pred)
    r2   = r2_score(y_true, y_pred)
    bias = float(np.mean(y_pred - y_true))
    return dict(model=label, MSE=round(mse,4), RMSE=round(rmse,4),
                MAE=round(mae,4), MedianAE=round(mdae,4),
                MAPE=round(mape,4), R2=round(r2,4), Bias=round(bias,4))

def compute_metrics_segmented(y_true, y_pred, label=""):
    y_true = np.array(y_true, dtype=float)
    y_pred = np.array(y_pred, dtype=float)
    segs = {
        "all":    np.ones(len(y_true), dtype=bool),
        "qty=1":  y_true == 1,
        "qty>1":  y_true > 1,
        "qty>=3": y_true >= 3,
    }
    rows = []
    for seg_name, mask in segs.items():
        n = mask.sum()
        if n == 0:
            continue
        yt, yp = y_true[mask], y_pred[mask]
        rows.append(dict(
            model=label, segment=seg_name, n=int(n),
            MAE=round(mean_absolute_error(yt, yp), 4),
            RMSE=round(np.sqrt(mean_squared_error(yt, yp)), 4),
            MedianAE=round(median_absolute_error(yt, yp), 4),
            Bias=round(float(np.mean(yp - yt)), 4)
        ))
    return rows

# Baseline predictions
pred_always1 = np.ones(len(y_test))
pred_median  = np.full(len(y_test), BASELINE_MEDIAN)
pred_mean    = np.full(len(y_test), BASELINE_MEAN)

baselines = {
    "Always-1"     : pred_always1,
    "Train-Median" : pred_median,
    "Train-Mean"   : pred_mean,
}

overall_results = []
seg_results = []

for name, pred in baselines.items():
    overall_results.append(compute_metrics(y_test, pred, name))
    seg_results.extend(compute_metrics_segmented(y_test, pred, name))

df_overall = pd.DataFrame(overall_results)
df_seg     = pd.DataFrame(seg_results)

print("\n── Baseline Metrics (Overall) ──")
display(df_overall)

print("\n── Baseline Metrics (Segmented) ──")
display(df_seg)

best_mae_baseline = df_overall.loc[df_overall["MAE"].idxmin(), "model"]
print(f"\n→ Best MAE baseline: {best_mae_baseline}")

Train median : 1.0
Train mean   : 1.3310

── Baseline Metrics (Overall) ──

          model     MSE    RMSE     MAE  MedianAE    MAPE      R2    Bias
0      Always-1  2.0083  1.4171  0.3508     0.000  0.1122 -0.0653 -0.3508
1  Train-Median  2.0083  1.4171  0.3508     0.000  0.1122 -0.0653 -0.3508
2    Train-Mean  1.8857  1.3732  0.5512     0.331  0.3498 -0.0002 -0.0198

── Baseline Metrics (Segmented) ──

           model segment      n     MAE    RMSE  MedianAE    Bias
0       Always-1     all  82403  0.3508  1.4171     0.000 -0.3508
1       Always-1   qty=1  66152  0.0000  0.0000     0.000  0.0000
2       Always-1   qty>1  16251  1.7785  3.1911     1.000 -1.7785
3       Always-1  qty>=3   4612  3.7433  5.7757     3.000 -3.7433
4   Train-Median     all  82403  0.3508  1.4171     0.000 -0.3508
5   Train-Median   qty=1  66152  0.0000  0.0000     0.000  0.0000
6   Train-Median   qty>1  16251  1.7785  3.1911     1.000 -1.7785
7   Train-Median  qty>=3   4612  3.7433  5.7757     3.000 -3.7433
8     Train-Mean     all  82403  0.5512  1.3732     0.331 -0.0198
9     Train-Mean   qty=1  66152  0.3310  0.3310     0.331  0.3310
10    Train-Mean   qty>1  16251  1.4476  3.0192     0.669 -1.4476
11    Train-Mean  qty>=3   4612  3.4123  5.5669     2.669 -3.4123

→ Best MAE baseline: Always-1

In [6]:
# ── PHASE 4 — HistGradientBoostingRegressor with OrdinalEncoding ───────────

CAT_COLS = [c for c in [
    "salesIndex", "category_norm", "pharmForm_norm", "campaignIndex_norm",
    "pid_segment", "group34", "price_diff_bin", "discount_bin"
] if c in X_train.columns]

NUM_COLS = [c for c in X_train.columns if c not in CAT_COLS]

print(f"Categorical features : {len(CAT_COLS)} → {CAT_COLS}")
print(f"Numerical features   : {len(NUM_COLS)}")

preprocessor = ColumnTransformer(transformers=[
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
     CAT_COLS),
    ("num", SimpleImputer(strategy="median"), NUM_COLS),
], remainder="drop")

hgb_model = HistGradientBoostingRegressor(
    max_iter=150,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

pipe_hgb = Pipeline([
    ("prep", preprocessor),
    ("model", hgb_model),
])

print("\nTraining HistGradientBoostingRegressor (max_iter=150)...")
t_start = time.time()
pipe_hgb.fit(X_train, y_train)
elapsed = time.time() - t_start
print(f"Training completed in {elapsed:.1f}s")

if elapsed > 900:
    print("WARNING: Training exceeded 15-minute threshold. Consider reducing max_iter.")

Categorical features : 8 → ['salesIndex', 'category_norm', 'pharmForm_norm', 'campaignIndex_norm', 'pid_segment', 'group34', 'price_diff_bin', 'discount_bin']
Numerical features   : 18

Training HistGradientBoostingRegressor (max_iter=150)...
Training completed in 6.3s

In [7]:
# ── PHASE 4 cont. — HistGB Predictions & Evaluation ───────────────────────

pred_hgb_raw     = pipe_hgb.predict(X_test)
pred_hgb_clipped = np.maximum(pred_hgb_raw, 1.0)

print("── HistGB Prediction Diagnostics ──")
print(f"  min raw      : {pred_hgb_raw.min():.4f}")
print(f"  max raw      : {pred_hgb_raw.max():.4f}")
print(f"  mean raw     : {pred_hgb_raw.mean():.4f}")
print(f"  n < 0        : {(pred_hgb_raw < 0).sum()}")
print(f"  n < 1        : {(pred_hgb_raw < 1).sum()}")

m_hgb_raw     = compute_metrics(y_test, pred_hgb_raw,     "HistGB_raw")
m_hgb_clipped = compute_metrics(y_test, pred_hgb_clipped, "HistGB_clipped")

overall_results.append(m_hgb_raw)
overall_results.append(m_hgb_clipped)

seg_results.extend(compute_metrics_segmented(y_test, pred_hgb_raw,     "HistGB_raw"))
seg_results.extend(compute_metrics_segmented(y_test, pred_hgb_clipped, "HistGB_clipped"))

df_overall = pd.DataFrame(overall_results)
df_seg     = pd.DataFrame(seg_results)

print("\n── Overall Metrics (Baselines + HistGB) ──")
display(df_overall.sort_values("MAE"))

print("\n── Segmented Metrics (Always-1 vs HistGB) ──")
display(df_seg[df_seg["model"].isin(["Always-1","HistGB_raw","HistGB_clipped"])].sort_values(["segment","MAE"]))

── HistGB Prediction Diagnostics ──
  min raw      : 1.1056
  max raw      : 29.6514
  mean raw     : 1.3363
  n < 0        : 0
  n < 1        : 0

── Overall Metrics (Baselines + HistGB) ──

            model     MSE    RMSE     MAE  MedianAE    MAPE      R2    Bias
0        Always-1  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
1    Train-Median  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
3      HistGB_raw  1.6805  1.2963  0.4953    0.2374  0.3106  0.1086 -0.0144
4  HistGB_clipped  1.6805  1.2963  0.4953    0.2374  0.3106  0.1086 -0.0144
2      Train-Mean  1.8857  1.3732  0.5512    0.3310  0.3498 -0.0002 -0.0198

── Segmented Metrics (Always-1 vs HistGB) ──

             model segment      n     MAE    RMSE  MedianAE    Bias
0         Always-1     all  82403  0.3508  1.4171    0.0000 -0.3508
12      HistGB_raw     all  82403  0.4953  1.2963    0.2374 -0.0144
16  HistGB_clipped     all  82403  0.4953  1.2963    0.2374 -0.0144
1         Always-1   qty=1  66152  0.0000  0.0000    0.0000  0.0000
13      HistGB_raw   qty=1  66152  0.2867  0.4182    0.2050  0.2867
17  HistGB_clipped   qty=1  66152  0.2867  0.4182    0.2050  0.2867
14      HistGB_raw   qty>1  16251  1.3444  2.7945    0.7955 -1.2404
18  HistGB_clipped   qty>1  16251  1.3444  2.7945    0.7955 -1.2404
2         Always-1   qty>1  16251  1.7785  3.1911    1.0000 -1.7785
15      HistGB_raw  qty>=3   4612  3.0398  5.1138    2.1901 -2.9107
19  HistGB_clipped  qty>=3   4612  3.0398  5.1138    2.1901 -2.9107
3         Always-1  qty>=3   4612  3.7433  5.7757    3.0000 -3.7433

In [8]:
# ── PHASE 5 — Optional Light Random Forest ────────────────────────────────
# Only run if HistGB shows clear RMSE advantage over Always-1

hgb_rmse     = df_overall.loc[df_overall["model"]=="HistGB_clipped","RMSE"].values[0]
always1_rmse = df_overall.loc[df_overall["model"]=="Always-1","RMSE"].values[0]
rmse_gain    = always1_rmse - hgb_rmse

print(f"Always-1 RMSE    : {always1_rmse:.4f}")
print(f"HistGB   RMSE    : {hgb_rmse:.4f}")
print(f"RMSE gain        : {rmse_gain:.4f}")

RUN_RF_LIGHT = rmse_gain > 0.05   # threshold: >0.05 RMSE improvement
print(f"\nRun Light RF?    : {RUN_RF_LIGHT}  (threshold: RMSE gain > 0.05)")

pred_rf_raw     = None
pred_rf_clipped = None

if RUN_RF_LIGHT:
    print("\nTraining Light RandomForestRegressor (n_estimators=30, max_depth=10)...")
    rf_model = RandomForestRegressor(
        n_estimators=30,
        max_depth=10,
        min_samples_leaf=50,
        random_state=42,
        n_jobs=-1
    )
    pipe_rf = Pipeline([
        ("prep", preprocessor),
        ("model", rf_model),
    ])
    t_rf = time.time()
    pipe_rf.fit(X_train, y_train)
    rf_elapsed = time.time() - t_rf
    print(f"RF training completed in {rf_elapsed:.1f}s")

    if rf_elapsed > 900:
        print("WARNING: RF exceeded 15-min threshold — results may be incomplete.")

    pred_rf_raw     = pipe_rf.predict(X_test)
    pred_rf_clipped = np.maximum(pred_rf_raw, 1.0)

    print(f"  min raw : {pred_rf_raw.min():.4f} | max : {pred_rf_raw.max():.4f} | mean : {pred_rf_raw.mean():.4f}")
    print(f"  n < 1   : {(pred_rf_raw < 1).sum()}")

    m_rf_raw     = compute_metrics(y_test, pred_rf_raw,     "RF_light_raw")
    m_rf_clipped = compute_metrics(y_test, pred_rf_clipped, "RF_light_clipped")
    overall_results.append(m_rf_raw)
    overall_results.append(m_rf_clipped)
    seg_results.extend(compute_metrics_segmented(y_test, pred_rf_raw,     "RF_light_raw"))
    seg_results.extend(compute_metrics_segmented(y_test, pred_rf_clipped, "RF_light_clipped"))

    df_overall = pd.DataFrame(overall_results)
    df_seg     = pd.DataFrame(seg_results)

    print("\n── Overall Metrics (all models) ──")
    display(df_overall.sort_values("MAE"))
else:
    print("\nSkipping Light RF — HistGB RMSE gain over Always-1 insufficient.")

Always-1 RMSE    : 1.4171
HistGB   RMSE    : 1.2963
RMSE gain        : 0.1208

Run Light RF?    : True  (threshold: RMSE gain > 0.05)

Training Light RandomForestRegressor (n_estimators=30, max_depth=10)...
RF training completed in 8.1s
  min raw : 1.0493 | max : 11.8443 | mean : 1.3395
  n < 1   : 0

── Overall Metrics (all models) ──

              model     MSE    RMSE     MAE  MedianAE    MAPE      R2    Bias
0          Always-1  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
1      Train-Median  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
6  RF_light_clipped  1.6354  1.2788  0.4840    0.2328  0.3041  0.1325 -0.0113
5      RF_light_raw  1.6354  1.2788  0.4840    0.2328  0.3041  0.1325 -0.0113
4    HistGB_clipped  1.6805  1.2963  0.4953    0.2374  0.3106  0.1086 -0.0144
3        HistGB_raw  1.6805  1.2963  0.4953    0.2374  0.3106  0.1086 -0.0144
2        Train-Mean  1.8857  1.3732  0.5512    0.3310  0.3498 -0.0002 -0.0198

In [9]:
# ── PHASE 6 — Decision Logic ───────────────────────────────────────────────

df_overall = pd.DataFrame(overall_results)
df_seg     = pd.DataFrame(seg_results)

print("=" * 65)
print("DECISION LOGIC — Primary: MAE | Secondary: RMSE, MedianAE, Bias")
print("=" * 65)

always1_metrics = df_overall[df_overall["model"] == "Always-1"].iloc[0]
a1_mae  = always1_metrics.MAE
a1_rmse = always1_metrics.RMSE
print(f"\nAlways-1  → MAE={a1_mae:.4f}  RMSE={a1_rmse:.4f}  R²={always1_metrics.R2:.4f}")

model_rows = df_overall[~df_overall["model"].isin(
    ["Always-1","Train-Median","Train-Mean","HistGB_raw","RF_light_raw"])].copy()

RECOMMENDATION = "Always-1"

if model_rows.empty:
    print("\nNo trained models available — Always-1 remains the strongest REG baseline.")
else:
    best_mae_row  = model_rows.loc[model_rows["MAE"].idxmin()]
    best_rmse_row = model_rows.loc[model_rows["RMSE"].idxmin()]

    print(f"\nBest model by MAE : {best_mae_row.model}  → MAE={best_mae_row.MAE:.4f}  RMSE={best_mae_row.RMSE:.4f}")
    print(f"Best model by RMSE: {best_rmse_row.model}  → MAE={best_rmse_row.MAE:.4f}  RMSE={best_rmse_row.RMSE:.4f}")

    mae_delta  = best_mae_row.MAE  - a1_mae
    rmse_delta = a1_rmse - best_rmse_row.RMSE

    print(f"\nMAE  delta (best_model - Always-1) : {mae_delta:+.4f}  ({'worse' if mae_delta>0 else 'better'})")
    print(f"RMSE delta (Always-1 - best_model) : {rmse_delta:+.4f}  ({'improvement' if rmse_delta>0 else 'no gain'})")

    # qty>1 segment
    a1_q1p  = df_seg[(df_seg["model"]=="Always-1") & (df_seg["segment"]=="qty>1")]
    bm_q1p  = df_seg[(df_seg["model"]==best_rmse_row.model) & (df_seg["segment"]=="qty>1")]
    if not a1_q1p.empty and not bm_q1p.empty:
        seg_delta = bm_q1p.iloc[0]["MAE"] - a1_q1p.iloc[0]["MAE"]
        print(f"\nqty>1 — Always-1 MAE={a1_q1p.iloc[0]['MAE']:.4f}  "
              f"{best_rmse_row.model} MAE={bm_q1p.iloc[0]['MAE']:.4f}  delta={seg_delta:+.4f}")

    print("\n── Rules ──")
    if mae_delta > 0.05:
        print(f"  → {best_mae_row.model} WORSENS MAE by {mae_delta:.4f} — Always-1 remains strongest baseline.")
        RECOMMENDATION = "Always-1"
    elif mae_delta > 0.01:
        if rmse_delta > 0.05:
            print(f"  → Slight MAE cost ({mae_delta:+.4f}) offset by RMSE gain ({rmse_delta:.4f}) → {best_rmse_row.model} is a candidate.")
            RECOMMENDATION = best_rmse_row.model
        else:
            print(f"  → Slight MAE degradation ({mae_delta:+.4f}), insufficient RMSE gain → Always-1 preferred.")
            RECOMMENDATION = "Always-1"
    else:
        if rmse_delta > 0.03:
            print(f"  → MAE similar ({mae_delta:+.4f}), meaningful RMSE gain ({rmse_delta:.4f}) → {best_rmse_row.model} is a candidate.")
            RECOMMENDATION = best_rmse_row.model
        else:
            print(f"  → No clear practical advantage — Always-1 remains strongest baseline.")
            RECOMMENDATION = "Always-1"

print(f"\n→ RECOMMENDATION: {RECOMMENDATION}")

=================================================================
DECISION LOGIC — Primary: MAE | Secondary: RMSE, MedianAE, Bias
=================================================================

Always-1  → MAE=0.3508  RMSE=1.4171  R²=-0.0653

Best model by MAE : RF_light_clipped  → MAE=0.4840  RMSE=1.2788
Best model by RMSE: RF_light_clipped  → MAE=0.4840  RMSE=1.2788

MAE  delta (best_model - Always-1) : +0.1332  (worse)
RMSE delta (Always-1 - best_model) : +0.1383  (improvement)

qty>1 — Always-1 MAE=1.7785  RF_light_clipped MAE=1.3138  delta=-0.4647

── Rules ──
  → RF_light_clipped WORSENS MAE by 0.1332 — Always-1 remains strongest baseline.

→ RECOMMENDATION: Always-1

In [10]:
# ── PHASE 7 — Visualizations ──────────────────────────────────────────────

# 1. quantity distribution
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
vc = y_train.value_counts().sort_index().head(20)
axes[0].bar(vc.index.astype(str), vc.values, color="steelblue", edgecolor="white")
axes[0].set_title("Train: quantity distribution (top 20 values)", fontsize=13)
axes[0].set_xlabel("quantity"); axes[0].set_ylabel("count")
vc_test = y_test.value_counts().sort_index().head(20)
axes[1].bar(vc_test.index.astype(str), vc_test.values, color="coral", edgecolor="white")
axes[1].set_title("Test: quantity distribution (top 20 values)", fontsize=13)
axes[1].set_xlabel("quantity"); axes[1].set_ylabel("count")
plt.tight_layout()
p = OUT_DIR / "minimal_reg_quantity_distribution.png"
plt.savefig(p, dpi=120, bbox_inches="tight")
plt.show(); print(f"Saved: {p.name}")

# 2. MAE / RMSE comparison
df_plot = df_overall[~df_overall["model"].str.contains("_raw")].copy().sort_values("MAE")
fig, ax = plt.subplots(figsize=(max(8, len(df_plot)*1.6), 5))
x = np.arange(len(df_plot)); w = 0.35
bars1 = ax.bar(x - w/2, df_plot["MAE"],  w, label="MAE",  color="steelblue")
bars2 = ax.bar(x + w/2, df_plot["RMSE"], w, label="RMSE", color="coral")
ax.set_xticks(x); ax.set_xticklabels(df_plot["model"], rotation=30, ha="right")
ax.set_ylabel("Error"); ax.set_title("MAE & RMSE — Minimal REG Run", fontsize=13)
ax.legend()
ax.bar_label(bars1, fmt="%.3f", fontsize=8, padding=2)
ax.bar_label(bars2, fmt="%.3f", fontsize=8, padding=2)
plt.tight_layout()
p = OUT_DIR / "minimal_reg_mae_rmse_comparison.png"
plt.savefig(p, dpi=120, bbox_inches="tight")
plt.show(); print(f"Saved: {p.name}")

Saved: minimal_reg_quantity_distribution.png
Saved: minimal_reg_mae_rmse_comparison.png

In [11]:
# ── PHASE 7 cont. — Scatterplots ─────────────────────────────────────────

def save_scatter(y_true, y_pred, model_name, filename, clip_axis=30):
    y_true = np.array(y_true, dtype=float)
    y_pred = np.array(y_pred, dtype=float)
    n_above = int((y_true > clip_axis).sum())
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(y_true, y_pred, alpha=0.15, s=4, color="steelblue", rasterized=True)
    lim = (0.5, clip_axis + 0.5)
    ax.plot(lim, lim, "r--", lw=1.5, label="y = x")
    ax.set_xlim(*lim); ax.set_ylim(*lim)
    ax.set_xlabel("Actual quantity"); ax.set_ylabel("Predicted quantity")
    ax.set_title(f"Scatter: {model_name}", fontsize=12)
    ax.text(0.98, 0.02, f"n > {clip_axis}: {n_above:,}", transform=ax.transAxes,
            ha="right", va="bottom", fontsize=9, color="gray")
    ax.legend(fontsize=9)
    plt.tight_layout()
    p = OUT_DIR / filename
    plt.savefig(p, dpi=120, bbox_inches="tight")
    plt.show(); print(f"Saved: {p.name}")

save_scatter(y_test, pred_hgb_clipped, "HistGB_clipped", "minimal_reg_scatter_histgb.png")

if pred_rf_clipped is not None:
    save_scatter(y_test, pred_rf_clipped, "RF_light_clipped", "minimal_reg_scatter_rf_light.png")
else:
    print("RF not run — no RF scatter.")

Saved: minimal_reg_scatter_histgb.png
Saved: minimal_reg_scatter_rf_light.png

In [12]:
# ── PHASE 7 cont. — Save CSVs ────────────────────────────────────────────

df_overall = pd.DataFrame(overall_results)
df_seg     = pd.DataFrame(seg_results)

p_overall = OUT_DIR / "minimal_reg_test_metrics_overall.csv"
df_overall.to_csv(p_overall, index=False)
print(f"Saved: {p_overall.name}")

p_seg = OUT_DIR / "minimal_reg_test_metrics_segmented.csv"
df_seg.to_csv(p_seg, index=False)
print(f"Saved: {p_seg.name}")

clipped_models = df_overall[df_overall["model"].str.contains("clipped|Always|Median|Mean")]
best_candidates = clipped_models.sort_values("MAE").head(5)
p_cand = OUT_DIR / "minimal_reg_best_candidates.csv"
best_candidates.to_csv(p_cand, index=False)
print(f"Saved: {p_cand.name}")
display(best_candidates)

pred_df = pd.DataFrame({
    "actual_quantity" : y_test.values,
    "pred_always1"    : pred_always1,
    "pred_median"     : pred_median,
    "pred_hgb_raw"    : pred_hgb_raw,
    "pred_hgb_clipped": pred_hgb_clipped,
})
if pred_rf_clipped is not None:
    pred_df["pred_rf_light_raw"]     = pred_rf_raw
    pred_df["pred_rf_light_clipped"] = pred_rf_clipped

p_pred = OUT_DIR / "minimal_reg_predictions.csv"
pred_df.to_csv(p_pred, index=False)
print(f"Saved: {p_pred.name}  ({len(pred_df):,} rows)")

Saved: minimal_reg_test_metrics_overall.csv
Saved: minimal_reg_test_metrics_segmented.csv
Saved: minimal_reg_best_candidates.csv

              model     MSE    RMSE     MAE  MedianAE    MAPE      R2    Bias
0          Always-1  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
1      Train-Median  2.0083  1.4171  0.3508    0.0000  0.1122 -0.0653 -0.3508
6  RF_light_clipped  1.6354  1.2788  0.4840    0.2328  0.3041  0.1325 -0.0113
4    HistGB_clipped  1.6805  1.2963  0.4953    0.2374  0.3106  0.1086 -0.0144
2        Train-Mean  1.8857  1.3732  0.5512    0.3310  0.3498 -0.0002 -0.0198

Saved: minimal_reg_predictions.csv  (82,403 rows)

In [13]:
# ── PHASE 8 — VAL Section (LOCKED) ───────────────────────────────────────
# FINAL REG HOLDOUT VALIDATION — DO NOT RUN UNTIL MODEL IS FIXED

RUN_FINAL_VAL = False

if RUN_FINAL_VAL:
    # VAL_PATH = DATA_DIR / "reg_val.csv"
    # val = pd.read_csv(VAL_PATH)
    raise RuntimeError(
        "VAL evaluation must be explicitly enabled. "
        "Set RUN_FINAL_VAL = True only after model is fixed."
    )
else:
    print("REG VAL is locked.")
    print("reg_val.csv was NOT loaded in this run.")

REG VAL is locked.
reg_val.csv was NOT loaded in this run.

In [14]:
# ── Assertions ────────────────────────────────────────────────────────────

assert train is not None and len(train) > 0,  "Train not loaded"
assert test  is not None and len(test)  > 0,  "Test not loaded"
assert TARGET in train.columns,                "quantity missing"
assert (y_train >= 1).all(),                   "quantity < 1 in train"
assert (y_test  >= 1).all(),                   "quantity < 1 in test"

for lc in LEAKAGE_COLS:
    assert lc not in X_train.columns, f"Leakage column '{lc}' still in X_train"

for fname in ["minimal_reg_test_metrics_overall.csv",
              "minimal_reg_test_metrics_segmented.csv",
              "minimal_reg_best_candidates.csv",
              "minimal_reg_predictions.csv"]:
    assert (OUT_DIR / fname).exists(), f"Missing output file: {fname}"

assert not RUN_FINAL_VAL,              "VAL guard violated"
assert len(df_seg) > 0,               "No segmented metrics"
assert "actual_quantity"  in pred_df.columns
assert "pred_hgb_clipped" in pred_df.columns

print("All assertions passed.")

All assertions passed.

## Phase 9 — Abschlussausgabe

In [15]:
# ── PHASE 9 — Abschlussausgabe ───────────────────────────────────────────

df_overall = pd.DataFrame(overall_results)
df_seg     = pd.DataFrame(seg_results)

sep = "=" * 65
print(sep)
print("  FINAL REG MINIMAL RUN — SUMMARY")
print(sep)

# 1. Stärkste Baseline nach MAE
baseline_only = df_overall[df_overall["model"].isin(["Always-1","Train-Median","Train-Mean"])]
best_base     = baseline_only.loc[baseline_only["MAE"].idxmin()]
print(f"\n1. Stärkste Baseline nach MAE : {best_base.model}  (MAE={best_base.MAE:.4f})")

# 2. Bestes Modell nach RMSE
clipped_models_df = df_overall[df_overall["model"].str.contains("clipped")]
if not clipped_models_df.empty:
    best_rmse_row = clipped_models_df.loc[clipped_models_df["RMSE"].idxmin()]
    print(f"2. Bestes Modell nach RMSE    : {best_rmse_row.model}  (RMSE={best_rmse_row.RMSE:.4f})")
else:
    best_rmse_row = None
    print("2. Kein Modell trainiert.")

# 3. Schlägt ein Modell Always-1 nach MAE?
a1_mae  = df_overall.loc[df_overall["model"]=="Always-1","MAE"].values[0]
a1_rmse = df_overall.loc[df_overall["model"]=="Always-1","RMSE"].values[0]
better_mae_df = clipped_models_df[clipped_models_df["MAE"] < a1_mae] if not clipped_models_df.empty else pd.DataFrame()
if not better_mae_df.empty:
    r = better_mae_df.iloc[0]
    print(f"3. MAE besser als Always-1    : JA → {r.model}  (MAE={r.MAE:.4f} vs {a1_mae:.4f})")
else:
    print(f"3. MAE besser als Always-1    : NEIN — Always-1 MAE={a1_mae:.4f} ist beste MAE.")

# 4. Schlägt ein Modell Always-1 nach RMSE?
better_rmse_df = clipped_models_df[clipped_models_df["RMSE"] < a1_rmse] if not clipped_models_df.empty else pd.DataFrame()
if not better_rmse_df.empty:
    r = better_rmse_df.iloc[0]
    print(f"4. RMSE besser als Always-1   : JA → {r.model}  (RMSE={r.RMSE:.4f} vs {a1_rmse:.4f})")
else:
    print(f"4. RMSE besser als Always-1   : NEIN — kein Modell schlägt Always-1 RMSE={a1_rmse:.4f}.")

# 5. qty>1 Segment
seg_a1  = df_seg[(df_seg["model"]=="Always-1") & (df_seg["segment"]=="qty>1")]
if not seg_a1.empty:
    a1_q1p_mae = seg_a1.iloc[0]["MAE"]
    print(f"5. qty>1 — Always-1 MAE={a1_q1p_mae:.4f}")
    if best_rmse_row is not None:
        seg_bm = df_seg[(df_seg["model"]==best_rmse_row.model) & (df_seg["segment"]=="qty>1")]
        if not seg_bm.empty:
            bm_q1p_mae = seg_bm.iloc[0]["MAE"]
            delta = bm_q1p_mae - a1_q1p_mae
            print(f"   {best_rmse_row.model} MAE={bm_q1p_mae:.4f}  delta={delta:+.4f}  "
                  f"({'besser' if delta<0 else 'schlechter'})")

# 6. Warum REG schwieriger als CLS?
print("""
6. Warum ist REG schwieriger als CLS?
   - Zielvariable (quantity) ist stark rechtsschief: Mehrheit quantity=1
   - Kein klares Signal für quantity>1 aus verfügbaren Features
   - RMSE wird von seltenen grossen Werten (quantity>>1) dominiert
   - Always-1 minimiert MAE, weil die Mehrheitsklasse quantity=1 ist
   - Modelle lernen bessere RMSE auf qty>1, erkaufen sich das
     aber mit schlechterer MAE auf dem dominanten qty=1-Segment
   - Strukturelles Problem: REG-Signal in diesen Daten ist schwach
""")

# 7. Empfehlung
print("7. Empfehlung:")
if RECOMMENDATION == "Always-1":
    print("   → a) Always-1 als finale REG-Baseline.")
    print("      Always-1 hat den besten MAE auf TEST.")
    print("      Kein Modell zeigt einen klaren praktischen Vorteil.")
    print("      Keine VAL-Freigabe nötig für Always-1 als Fallback.")
else:
    print(f"   → b) {RECOMMENDATION} als finaler REG-Kandidat.")
    print(f"      Klarer RMSE-Vorteil über Always-1 nachgewiesen.")
    print(f"      VAL-Freigabe empfohlen, bevor {RECOMMENDATION} als final gilt.")
    print(f"      Weiterer Vergleich mit Always-1 auf VAL ausstehend.")

print(f"\n   REG VAL bleibt gesperrt (RUN_FINAL_VAL={RUN_FINAL_VAL}).")
print(sep)

=================================================================
  FINAL REG MINIMAL RUN — SUMMARY
=================================================================

1. Stärkste Baseline nach MAE : Always-1  (MAE=0.3508)
2. Bestes Modell nach RMSE    : RF_light_clipped  (RMSE=1.2788)
3. MAE besser als Always-1    : NEIN — Always-1 MAE=0.3508 ist beste MAE.
4. RMSE besser als Always-1   : JA → HistGB_clipped  (RMSE=1.2963 vs 1.4171)
5. qty>1 — Always-1 MAE=1.7785
   RF_light_clipped MAE=1.3138  delta=-0.4647  (besser)

6. Warum ist REG schwieriger als CLS?
   - Zielvariable (quantity) ist stark rechtsschief: Mehrheit quantity=1
   - Kein klares Signal für quantity>1 aus verfügbaren Features
   - RMSE wird von seltenen grossen Werten (quantity>>1) dominiert
   - Always-1 minimiert MAE, weil die Mehrheitsklasse quantity=1 ist
   - Modelle lernen bessere RMSE auf qty>1, erkaufen sich das
     aber mit schlechterer MAE auf dem dominanten qty=1-Segment
   - Strukturelles Problem: REG-Signal in diesen Daten ist schwach

7. Empfehlung:
   → a) Always-1 als finale REG-Baseline.
      Always-1 hat den besten MAE auf TEST.
      Kein Modell zeigt einen klaren praktischen Vorteil.
      Keine VAL-Freigabe nötig für Always-1 als Fallback.

   REG VAL bleibt gesperrt (RUN_FINAL_VAL=False).
=================================================================

---
## FINALE REG HOLDOUT-BEWERTUNG — VAL

**Einmalige Auswertung auf reg_val.csv. Kein Tuning. Kein neues Modell.**

Fixierte Kandidaten:
- **Always-1** (Baseline)
- **RF_light_clipped** (n_estimators=30, max_depth=10, min_samples_leaf=50, random_state=42)

TEST-Referenzwerte:
| Variante | MAE | RMSE | R² | qty>1 MAE |
|---|---|---|---|---|
| Always-1 | 0.3508 | 1.4171 | -0.065 | 1.7785 |
| RF_light_clipped | 0.4840 | 1.2788 | 0.078 | 1.3138 |

In [16]:
# ── VAL 1 — Load reg_val.csv ──────────────────────────────────────────────
VAL_PATH = DATA_DIR / "reg_val.csv"
print(f"Loading VAL: {VAL_PATH}")

t0 = time.time()
val = pd.read_csv(VAL_PATH)
print(f"Loaded in {time.time()-t0:.1f}s")
print(f"\nVAL shape : {val.shape}")

# quantity checks
assert TARGET in val.columns, "quantity missing from val"
y_val = val[TARGET].copy()
assert (y_val >= 1).all(), "quantity < 1 in VAL"

qty_summary(y_val, "VAL")

# Leakage check and feature alignment
X_val = val.drop(columns=[c for c in DROP_COLS if c in val.columns])
X_val = X_val[[c for c in shared_cols if c in X_val.columns]]
missing_cols = [c for c in shared_cols if c not in X_val.columns]
assert not missing_cols, f"VAL missing feature columns: {missing_cols}"
assert list(X_val.columns) == list(X_train.columns), "VAL/TRAIN column mismatch"

for lc in LEAKAGE_COLS:
    assert lc not in X_val.columns, f"Leakage column '{lc}' still in X_val"

print(f"\nX_val shape : {X_val.shape}")
print("Column alignment TRAIN ↔ VAL: OK")
print("Leakage check: OK")

Loading VAL: c:\Users\karim\OneDrive - FHNW\Documents\Analytics Project Code\Feature Engineering\outputs\orange_exports\reg_val.csv
Loaded in 0.3s

VAL shape : (87746, 27)

── VAL quantity ──
  n        : 87,746
  mean     : 1.3400
  median   : 1.0000
  min      : 1.0
  max      : 100.0
  p95      : 3.00
  p99      : 5.00
  qty=1    : 80.5%  (70,676)
  qty>1    : 19.5%  (17,070)
  qty>=3   : 5.4%  (4,779)

X_val shape : (87746, 26)
Column alignment TRAIN ↔ VAL: OK
Leakage check: OK

In [17]:
# ── VAL 2 — Retrain RF_light on reg_train_full.csv (identical pipeline) ────
# Same parameters as TEST run — no tuning, no changes
print("Retraining RF_light pipeline on reg_train_full.csv...")
print("Parameters: n_estimators=30, max_depth=10, min_samples_leaf=50, random_state=42")

preprocessor_val = ColumnTransformer(transformers=[
    ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1),
     CAT_COLS),
    ("num", SimpleImputer(strategy="median"), NUM_COLS),
], remainder="drop")

pipe_rf_val = Pipeline([
    ("prep", preprocessor_val),
    ("model", RandomForestRegressor(
        n_estimators=30,
        max_depth=10,
        min_samples_leaf=50,
        random_state=42,
        n_jobs=-1
    )),
])

t_val = time.time()
pipe_rf_val.fit(X_train, y_train)
rf_val_elapsed = time.time() - t_val
print(f"Training completed in {rf_val_elapsed:.1f}s")

if rf_val_elapsed > 900:
    print("WARNING: Exceeded 15-minute threshold.")

Retraining RF_light pipeline on reg_train_full.csv...
Parameters: n_estimators=30, max_depth=10, min_samples_leaf=50, random_state=42
Training completed in 7.5s

In [18]:
# ── VAL 3 — Predictions & Diagnostics ────────────────────────────────────

# Always-1
pred_val_always1 = np.ones(len(y_val))

# RF_light_clipped
pred_val_rf_raw     = pipe_rf_val.predict(X_val)
pred_val_rf_clipped = np.maximum(pred_val_rf_raw, 1.0)

print("── RF_light VAL Prediction Diagnostics ──")
print(f"  min raw      : {pred_val_rf_raw.min():.4f}")
print(f"  max raw      : {pred_val_rf_raw.max():.4f}")
print(f"  mean raw     : {pred_val_rf_raw.mean():.4f}")
print(f"  n < 0        : {(pred_val_rf_raw < 0).sum()}")
print(f"  n < 1        : {(pred_val_rf_raw < 1).sum()}")
print(f"  n clipped    : {(pred_val_rf_clipped > pred_val_rf_raw).sum()}")

── RF_light VAL Prediction Diagnostics ──
  min raw      : 1.0493
  max raw      : 12.9094
  mean raw     : 1.3450
  n < 0        : 0
  n < 1        : 0
  n clipped    : 0

In [19]:
# ── VAL 4 — Metrics on VAL ───────────────────────────────────────────────

val_candidates = {
    "Always-1"        : pred_val_always1,
    "RF_light_clipped": pred_val_rf_clipped,
}

val_overall_results = []
val_seg_results     = []

for name, pred in val_candidates.items():
    val_overall_results.append(compute_metrics(y_val, pred, name))
    val_seg_results.extend(compute_metrics_segmented(y_val, pred, name))

df_val_overall = pd.DataFrame(val_overall_results)
df_val_seg     = pd.DataFrame(val_seg_results)

print("── VAL Overall Metrics ──")
display(df_val_overall)

print("\n── VAL Segmented Metrics ──")
display(df_val_seg)

── VAL Overall Metrics ──

              model     MSE    RMSE     MAE  MedianAE    MAPE      R2   Bias
0          Always-1  1.8904  1.3749  0.3400    0.0000  0.1105 -0.0652 -0.340
1  RF_light_clipped  1.5472  1.2439  0.4792    0.2328  0.3076  0.1282  0.005

── VAL Segmented Metrics ──

              model segment      n     MAE    RMSE  MedianAE    Bias
0          Always-1     all  87746  0.3400  1.3749    0.0000 -0.3400
1          Always-1   qty=1  70676  0.0000  0.0000    0.0000  0.0000
2          Always-1   qty>1  17070  1.7480  3.1173    1.0000 -1.7480
3          Always-1  qty>=3   4779  3.6717  5.6690    3.0000 -3.6717
4  RF_light_clipped     all  87746  0.4792  1.2439    0.2328  0.0050
5  RF_light_clipped   qty=1  70676  0.2855  0.4405    0.1954  0.2855
6  RF_light_clipped   qty>1  17070  1.2812  2.6739    0.8046 -1.1567
7  RF_light_clipped  qty>=3   4779  2.8471  4.9119    2.0219 -2.7681

In [20]:
# ── VAL 5 — Save Outputs ─────────────────────────────────────────────────

# Overall metrics
p = OUT_DIR / "final_reg_val_metrics_overall.csv"
df_val_overall.to_csv(p, index=False)
print(f"Saved: {p.name}")

# Segmented metrics
p = OUT_DIR / "final_reg_val_metrics_segmented.csv"
df_val_seg.to_csv(p, index=False)
print(f"Saved: {p.name}")

# Predictions
val_pred_df = pd.DataFrame({
    "actual_quantity"  : y_val.values,
    "pred_always1"     : pred_val_always1,
    "pred_rf_light_raw": pred_val_rf_raw,
    "pred_rf_clipped"  : pred_val_rf_clipped,
})
p = OUT_DIR / "final_reg_val_predictions.csv"
val_pred_df.to_csv(p, index=False)
print(f"Saved: {p.name}  ({len(val_pred_df):,} rows)")

# Diagnostics
diag_rows = []
for name, pred_arr in [("Always-1", pred_val_always1),
                        ("RF_light_clipped", pred_val_rf_clipped)]:
    pred_arr = np.array(pred_arr, dtype=float)
    y_arr    = np.array(y_val, dtype=float)
    diag_rows.append(dict(
        model=name,
        n_predictions=len(pred_arr),
        min_pred=round(pred_arr.min(), 4),
        max_pred=round(pred_arr.max(), 4),
        mean_pred=round(pred_arr.mean(), 4),
        n_below_1=int((pred_arr < 1).sum()),
        n_above_10=int((pred_arr > 10).sum()),
        n_above_30=int((pred_arr > 30).sum()),
    ))
df_diag = pd.DataFrame(diag_rows)
p = OUT_DIR / "final_reg_val_prediction_diagnostics.csv"
df_diag.to_csv(p, index=False)
print(f"Saved: {p.name}")
display(df_diag)

Saved: final_reg_val_metrics_overall.csv
Saved: final_reg_val_metrics_segmented.csv
Saved: final_reg_val_predictions.csv  (87,746 rows)
Saved: final_reg_val_prediction_diagnostics.csv

,model,n_predictions,min_pred,max_pred,mean_pred,n_below_1,n_above_10,n_above_30
0,Always-1,87746,1.0000,1.0000,1.000,0,0,0
1,RF_light_clipped,87746,1.0493,12.9094,1.345,0,31,0

In [21]:
# ── VAL 6 — TEST vs. VAL Comparison ──────────────────────────────────────

# TEST reference values (from completed TEST run)
TEST_REF = {
    "Always-1": {
        "MAE": 0.3508, "RMSE": 1.4171, "R2": -0.065,
        "Bias": 0.0, "qty_gt1_MAE": 1.7785
    },
    "RF_light_clipped": {
        "MAE": 0.4840, "RMSE": 1.2788, "R2": 0.078,
        "Bias": None, "qty_gt1_MAE": 1.3138
    },
}

print("=" * 75)
print("  TEST vs. VAL COMPARISON")
print("=" * 75)

comparison_rows = []
for model_name in ["Always-1", "RF_light_clipped"]:
    ref  = TEST_REF[model_name]
    val_row = df_val_overall[df_val_overall["model"] == model_name].iloc[0]
    seg_q1p = df_val_seg[(df_val_seg["model"] == model_name) & (df_val_seg["segment"] == "qty>1")]
    val_q1p_mae = seg_q1p.iloc[0]["MAE"] if not seg_q1p.empty else None

    delta_mae  = round(val_row["MAE"]  - ref["MAE"],  4)
    delta_rmse = round(val_row["RMSE"] - ref["RMSE"], 4)
    delta_r2   = round(val_row["R2"]   - ref["R2"],   4)
    delta_bias = round(val_row["Bias"] - (ref["Bias"] if ref["Bias"] is not None else val_row["Bias"]), 4)
    delta_q1p  = round(val_q1p_mae - ref["qty_gt1_MAE"], 4) if val_q1p_mae is not None else None

    comparison_rows.append(dict(
        model=model_name,
        TEST_MAE=ref["MAE"],   VAL_MAE=round(val_row["MAE"],4),   delta_MAE=delta_mae,
        TEST_RMSE=ref["RMSE"], VAL_RMSE=round(val_row["RMSE"],4), delta_RMSE=delta_rmse,
        TEST_R2=ref["R2"],     VAL_R2=round(val_row["R2"],4),     delta_R2=delta_r2,
        TEST_qty_gt1_MAE=ref["qty_gt1_MAE"],
        VAL_qty_gt1_MAE=val_q1p_mae,
        delta_qty_gt1_MAE=delta_q1p,
    ))

    print(f"\n{'─'*60}")
    print(f"  {model_name}")
    print(f"{'─'*60}")
    print(f"  MAE  : TEST={ref['MAE']:.4f}  VAL={val_row['MAE']:.4f}  Δ={delta_mae:+.4f}")
    print(f"  RMSE : TEST={ref['RMSE']:.4f}  VAL={val_row['RMSE']:.4f}  Δ={delta_rmse:+.4f}")
    print(f"  R²   : TEST={ref['R2']:.4f}   VAL={val_row['R2']:.4f}   Δ={delta_r2:+.4f}")
    print(f"  Bias : VAL={val_row['Bias']:.4f}")
    if val_q1p_mae is not None:
        print(f"  qty>1 MAE : TEST={ref['qty_gt1_MAE']:.4f}  VAL={val_q1p_mae:.4f}  Δ={delta_q1p:+.4f}")

df_comparison = pd.DataFrame(comparison_rows)
print("\n── Comparison Table ──")
display(df_comparison)

===========================================================================
  TEST vs. VAL COMPARISON
===========================================================================

────────────────────────────────────────────────────────────
  Always-1
────────────────────────────────────────────────────────────
  MAE  : TEST=0.3508  VAL=0.3400  Δ=-0.0108
  RMSE : TEST=1.4171  VAL=1.3749  Δ=-0.0422
  R²   : TEST=-0.0650   VAL=-0.0652   Δ=-0.0002
  Bias : VAL=-0.3400
  qty>1 MAE : TEST=1.7785  VAL=1.7480  Δ=-0.0305

────────────────────────────────────────────────────────────
  RF_light_clipped
────────────────────────────────────────────────────────────
  MAE  : TEST=0.4840  VAL=0.4792  Δ=-0.0048
  RMSE : TEST=1.2788  VAL=1.2439  Δ=-0.0349
  R²   : TEST=0.0780   VAL=0.1282   Δ=+0.0502
  Bias : VAL=0.0050
  qty>1 MAE : TEST=1.3138  VAL=1.2812  Δ=-0.0326

── Comparison Table ──

,model,TEST_MAE,VAL_MAE,delta_MAE,TEST_RMSE,VAL_RMSE,delta_RMSE,TEST_R2,VAL_R2,delta_R2,TEST_qty_gt1_MAE,VAL_qty_gt1_MAE,delta_qty_gt1_MAE
0,Always-1,0.3508,0.3400,-0.0108,1.4171,1.3749,-0.0422,-0.065,-0.0652,-0.0002,1.7785,1.7480,-0.0305
1,RF_light_clipped,0.4840,0.4792,-0.0048,1.2788,1.2439,-0.0349,0.078,0.1282,0.0502,1.3138,1.2812,-0.0326

## VAL 7 — Interpretation & REG-Abschluss

In [22]:
# ── VAL 7 — Interpretation & REG-Abschluss ───────────────────────────────

df_val_overall = pd.DataFrame(val_overall_results)
df_val_seg     = pd.DataFrame(val_seg_results)

a1_val  = df_val_overall[df_val_overall["model"]=="Always-1"].iloc[0]
rf_val  = df_val_overall[df_val_overall["model"]=="RF_light_clipped"].iloc[0]

a1_val_q1p = df_val_seg[(df_val_seg["model"]=="Always-1")         & (df_val_seg["segment"]=="qty>1")].iloc[0]
rf_val_q1p = df_val_seg[(df_val_seg["model"]=="RF_light_clipped") & (df_val_seg["segment"]=="qty>1")].iloc[0]

sep = "=" * 70
print(sep)
print("  FINALE REG-HOLDOUT-INTERPRETATION")
print(sep)

# 1. Generalisierung
print("\n1. Generalisieren beide Varianten stabil?")
a1_mae_delta  = round(a1_val.MAE  - 0.3508, 4)
a1_rmse_delta = round(a1_val.RMSE - 1.4171, 4)
rf_mae_delta  = round(rf_val.MAE  - 0.4840, 4)
rf_rmse_delta = round(rf_val.RMSE - 1.2788, 4)
print(f"   Always-1        : MAE Δ={a1_mae_delta:+.4f}  RMSE Δ={a1_rmse_delta:+.4f}")
print(f"   RF_light_clipped: MAE Δ={rf_mae_delta:+.4f}  RMSE Δ={rf_rmse_delta:+.4f}")
thr = 0.05
a1_stable = abs(a1_mae_delta) < thr and abs(a1_rmse_delta) < thr
rf_stable = abs(rf_mae_delta) < thr and abs(rf_rmse_delta) < thr
print(f"   → Always-1 stabil: {'JA' if a1_stable else 'NEIN (Drift erkennbar)'}")
print(f"   → RF_light stabil: {'JA' if rf_stable else 'NEIN (Drift erkennbar)'}")

# 2. Always-1 nach MAE stärkste Variante?
print(f"\n2. Bleibt Always-1 nach MAE stärkste Variante auf VAL?")
print(f"   Always-1 MAE={a1_val.MAE:.4f}  vs  RF_light_clipped MAE={rf_val.MAE:.4f}")
if a1_val.MAE <= rf_val.MAE:
    print(f"   → JA — Always-1 hat den besten MAE auf VAL.")
else:
    print(f"   → NEIN — RF_light_clipped hat einen besseren MAE auf VAL ({rf_val.MAE:.4f} vs {a1_val.MAE:.4f}).")

# 3. RF_light_clipped bei RMSE und qty>1 besser?
print(f"\n3. Bleibt RF_light_clipped bei RMSE und qty>1 besser?")
print(f"   RMSE : Always-1={a1_val.RMSE:.4f}  RF_light={rf_val.RMSE:.4f}  Δ={a1_val.RMSE-rf_val.RMSE:+.4f}")
print(f"   qty>1 MAE: Always-1={a1_val_q1p.MAE:.4f}  RF_light={rf_val_q1p.MAE:.4f}  Δ={a1_val_q1p.MAE-rf_val_q1p.MAE:+.4f}")
if rf_val.RMSE < a1_val.RMSE and rf_val_q1p.MAE < a1_val_q1p.MAE:
    print(f"   → JA — RF_light_clipped ist bei RMSE und qty>1 besser als Always-1.")
elif rf_val.RMSE < a1_val.RMSE:
    print(f"   → Teilweise — RF_light besser bei RMSE, aber nicht bei qty>1 MAE.")
else:
    print(f"   → NEIN — RF_light_clipped ist weder bei RMSE noch qty>1 besser auf VAL.")

# 4. Fachliche Sinnhaftigkeit
print(f"""
4. Welche Variante ist fachlich sinnvoller für die Two-Stage-Architektur?

   Kontext: In der Two-Stage-Architektur sagt CLS (Stage 1) bereits voraus,
   ob ein Kauf stattfindet. REG (Stage 2) soll nur für Kaufereignisse die
   Menge vorhersagen.

   - Always-1 ist ehrlicher: ~81% der Kaufereignisse sind tatsächlich qty=1.
     Die Vorhersage trifft die Mehrheitsklasse perfekt und vermeidet
     systematische Über- oder Unterschätzung.

   - RF_light_clipped gewinnt RMSE und bildet qty>1 besser ab, bezahlt das
     aber mit ~0.13 schlechterer MAE — hauptsächlich weil es qty=1 leicht
     überschätzt und damit die dominante Klasse verschlechtert.

   Für Dynamic Pricing ist die Frage:
   → Wenn die Preisentscheidung linear von der Mengenprognose abhängt,
     ist MAE die richtige Metrik → Always-1 ist fachlich stabiler.
   → Wenn grosse Mengen (qty>=3) wirtschaftlich überproportional gewichtet
     werden, könnte RF_light_clipped trotzdem nützlich sein.
""")

# 5. Ist komplexe Mengenmodellierung gerechtfertigt?
print("5. Ist eine komplexe Mengenmodellierung gerechtfertigt oder Always-1 ehrlicher?")
mae_gap = rf_val.MAE - a1_val.MAE
rmse_gap = a1_val.RMSE - rf_val.RMSE
print(f"   MAE-Kosten RF_light vs Always-1 : +{mae_gap:.4f}")
print(f"   RMSE-Gewinn RF_light vs Always-1: -{rmse_gap:.4f}")
print(f"""
   → REG ist strukturell schwierig: Das Signal für qty>1 ist in den
     verfügbaren Features schwach. Mit ~81% qty=1-Anteil ist Always-1
     statistisch optimal für MAE.
     Ein RF mit 30 Trees und OrdinalEncoding verbessert RMSE und qty>1,
     aber kann das strukturelle Problem nicht lösen.

   → Always-1 ist als finale REG-Baseline ehrlicher und verteidigbar.
     Eine komplexe Mengenmodellierung wäre nur gerechtfertigt, wenn
     neue Features mit echtem Mengensignal (z. B. Packungsgrösse,
     historische Mengen-Patterns) verfügbar wären.
""")

# 6. Final verdict
print(sep)
print("  REG FINAL VERDICT")
print(sep)
print(f"\n  Always-1 VAL  → MAE={a1_val.MAE:.4f}  RMSE={a1_val.RMSE:.4f}  R²={a1_val.R2:.4f}")
print(f"  RF_light VAL  → MAE={rf_val.MAE:.4f}  RMSE={rf_val.RMSE:.4f}  R²={rf_val.R2:.4f}")
print()
if a1_val.MAE <= rf_val.MAE:
    print("  FINALE EMPFEHLUNG: Always-1 als REG-Baseline")
    print("  Begründung: Bester MAE auf TEST und VAL. Stabiles Generalisierungsverhalten.")
    print("  RF_light als Zusatzinformation für qty>1-Segment dokumentiert.")
else:
    print(f"  FINALE EMPFEHLUNG: RF_light_clipped als REG-Kandidat")
    print(f"  Begründung: Auf VAL auch MAE besser ({rf_val.MAE:.4f} vs {a1_val.MAE:.4f}).")
    print(f"  Klare Überlegenheit auf beiden Splits → kann Always-1 ersetzen.")
print()
print("  REG-Evaluation abgeschlossen. Keine Nachoptimierung.")
print(sep)

======================================================================
  FINALE REG-HOLDOUT-INTERPRETATION
======================================================================

1. Generalisieren beide Varianten stabil?
   Always-1        : MAE Δ=-0.0108  RMSE Δ=-0.0422
   RF_light_clipped: MAE Δ=-0.0048  RMSE Δ=-0.0349
   → Always-1 stabil: JA
   → RF_light stabil: JA

2. Bleibt Always-1 nach MAE stärkste Variante auf VAL?
   Always-1 MAE=0.3400  vs  RF_light_clipped MAE=0.4792
   → JA — Always-1 hat den besten MAE auf VAL.

3. Bleibt RF_light_clipped bei RMSE und qty>1 besser?
   RMSE : Always-1=1.3749  RF_light=1.2439  Δ=+0.1310
   qty>1 MAE: Always-1=1.7480  RF_light=1.2812  Δ=+0.4668
   → JA — RF_light_clipped ist bei RMSE und qty>1 besser als Always-1.

4. Welche Variante ist fachlich sinnvoller für die Two-Stage-Architektur?

   Kontext: In der Two-Stage-Architektur sagt CLS (Stage 1) bereits voraus,
   ob ein Kauf stattfindet. REG (Stage 2) soll nur für Kaufereignisse die
   Menge vorhersagen.

   - Always-1 ist ehrlicher: ~81% der Kaufereignisse sind tatsächlich qty=1.
     Die Vorhersage trifft die Mehrheitsklasse perfekt und vermeidet
     systematische Über- oder Unterschätzung.

   - RF_light_clipped gewinnt RMSE und bildet qty>1 besser ab, bezahlt das
     aber mit ~0.13 schlechterer MAE — hauptsächlich weil es qty=1 leicht
     überschätzt und damit die dominante Klasse verschlechtert.

   Für Dynamic Pricing ist die Frage:
   → Wenn die Preisentscheidung linear von der Mengenprognose abhängt,
     ist MAE die richtige Metrik → Always-1 ist fachlich stabiler.
   → Wenn grosse Mengen (qty>=3) wirtschaftlich überproportional gewichtet
     werden, könnte RF_light_clipped trotzdem nützlich sein.

5. Ist eine komplexe Mengenmodellierung gerechtfertigt oder Always-1 ehrlicher?
   MAE-Kosten RF_light vs Always-1 : +0.1392
   RMSE-Gewinn RF_light vs Always-1: -0.1310

   → REG ist strukturell schwierig: Das Signal für qty>1 ist in den
     verfügbaren Features schwach. Mit ~81% qty=1-Anteil ist Always-1
     statistisch optimal für MAE.
     Ein RF mit 30 Trees und OrdinalEncoding verbessert RMSE und qty>1,
     aber kann das strukturelle Problem nicht lösen.

   → Always-1 ist als finale REG-Baseline ehrlicher und verteidigbar.
     Eine komplexe Mengenmodellierung wäre nur gerechtfertigt, wenn
     neue Features mit echtem Mengensignal (z. B. Packungsgrösse,
     historische Mengen-Patterns) verfügbar wären.

======================================================================
  REG FINAL VERDICT
======================================================================

  Always-1 VAL  → MAE=0.3400  RMSE=1.3749  R²=-0.0652
  RF_light VAL  → MAE=0.4792  RMSE=1.2439  R²=0.1282

  FINALE EMPFEHLUNG: Always-1 als REG-Baseline
  Begründung: Bester MAE auf TEST und VAL. Stabiles Generalisierungsverhalten.
  RF_light als Zusatzinformation für qty>1-Segment dokumentiert.

  REG-Evaluation abgeschlossen. Keine Nachoptimierung.
======================================================================